#!/usr/bin/env python3

import time
import openarm_can as oa

openarm = oa.OpenArm('can2', True)
openarm.init_arm_motors(
    [oa.MotorType.DM8009, oa.MotorType.DM8009, oa.MotorType.DM4340, oa.MotorType.DM4340,
     oa.MotorType.DM4310, oa.MotorType.DM4310, oa.MotorType.DM4310],
    [0x01, 0x02, 0x03, 0x04, 0x05, 0x06, 0x07],
    [0x11, 0x12, 0x13, 0x14, 0x15, 0x16, 0x17]
)

openarm.init_gripper_motor(oa.MotorType.DM4310, 0x08, 0x18)
openarm.set_callback_mode_all(oa.CallbackMode.STATE)

openarm.enable_all()
print("Enabled")
time.sleep(3)
openarm.enable_all()
print("done, check candump")
